apiVersion: v1
kind: Service
mestadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
  spec:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 32000
    selector:
      name: voting-app-pod
      app: demo-voting-app